# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ILM.qmd 

      - name: Archive pdf output
        uses: actions/upload-artifact@v4
        with:
          name: pdf-output
          path: ILM.pdf






